# Device name mappings: source folder → target device category
devices:
  00_raw_sources/sony-fx-3: CAM_fx3
  00_raw_sources/sony-fx-30: CAM_fx30
  00_raw_sources/sony-zv-e10: CAM_zv-e10
  00_raw_sources/dji-osmo-pocket-3: CAM_osmo-pocket-3
  00_raw_sources/dji-osmo-pocket-3-mic: AUDIO_osmo-pocket-3-mic
  00_raw_sources/dji-mic-2: AUDIO_dji-mic-2
  00_raw_sources/zoom-fr: AUDIO_zoom-fr
  00_raw_sources/audio-tracks: AUDIO_dji-mic-2

riverside:
  enabled: true
  device_name: CAM_riverside
  source_patterns:
    - "aipe-footage/*/00-raw/video/*.MP4"
    - "aipe-footage/*/00-raw/video/*.mp4"

projects:
  - name: aipe-footage
    source_path: aipe-footage
    target_path: /Projects/aipe
    preserve_structure: true
  
  - name: video_mama_2025
    source_path: video_mama_2025
    target_path: /Projects/video_mama_2025
    preserve_structure: true
  
  - name: capcut
    source_path: capcut
    target_path: /Projects/capcut/renders
    preserve_structure: false
    exclude_patterns:
      - "User Data/*"
  
  - name: billionblog
    source_path: billionblog
    target_path: /Projects/billionblog
    preserve_structure: true

audio_tracks:
  source_path: audio-tracks
  target_base: /Originals/AUDIO_dji-mic-2
  extract_date_from_filename: true
  filename_pattern: "DJI_\\d+_(\\d{8})_\\d+\\.WAV"

exclude:
  - ".DS_Store"
  - "*.db"
  - "*.db-journal"
  - ".sync_*"
  - ".DocumentRevisions-V100"
  - ".fseventsd"
  - ".Spotlight-V100"
  - ".TemporaryItems"
  - ".Trashes"
  - "capcut/User Data"
  - "*.tmp"
  - "*.temp"

file_types:
  video:
    extensions: [".mp4", ".MP4", ".mov", ".MOV", ".avi", ".mkv"]
  audio:
    extensions: [".wav", ".WAV", ".mp3", ".MP3", ".aac", ".flac"]
  image:
    extensions: [".jpg", ".JPG", ".jpeg", ".png", ".raw", ".RAW", ".dng"]
  metadata:
    extensions: [".xml", ".XML", ".json", ".yaml"]

duplicates:
  priority:
    - "/Originals/CAM_*"
    - "/Originals/AUDIO_*"
    - "/Projects/aipe"
    - "/Projects/*"
  action: "symlink"
  min_size_bytes: 1048576
