#!/bin/bash
set -euo pipefail

# Terminal colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ $# -ne 1 ]; then
    echo "Usage: $0 <target_volume>"
    echo "Example: $0 /Volumes/RodNAS/Media"
    exit 1
fi

TARGET="$1"

if [ ! -d "$TARGET" ]; then
    echo "Error: Target volume does not exist: $TARGET"
    echo "Is your NAS connected and mounted?"
    exit 1
fi

echo -e "${BLUE}Creating folder structure at: $TARGET${NC}"

# Main structure
mkdir -p "$TARGET/_ingest"
mkdir -p "$TARGET/Originals"
mkdir -p "$TARGET/Projects"
mkdir -p "$TARGET/Catalog/sidecars"
mkdir -p "$TARGET/Catalog/transcripts"
mkdir -p "$TARGET/Catalog/thumbs"
mkdir -p "$TARGET/Catalog/hashes"

# Originals - Camera folders
for year in 2024 2025; do
    mkdir -p "$TARGET/Originals/CAM_fx3/$year"
    mkdir -p "$TARGET/Originals/CAM_fx30/$year"
    mkdir -p "$TARGET/Originals/CAM_zv-e10/$year"
    mkdir -p "$TARGET/Originals/CAM_osmo-pocket-3/$year"
    mkdir -p "$TARGET/Originals/CAM_riverside/$year"
done

# Originals - Audio folders
for year in 2024 2025; do
    mkdir -p "$TARGET/Originals/AUDIO_zoom-f3/$year"
    mkdir -p "$TARGET/Originals/AUDIO_dji-mic-2/$year"
done

# Projects structure
mkdir -p "$TARGET/Projects/aipe"
mkdir -p "$TARGET/Projects/capcut/renders"
mkdir -p "$TARGET/Projects/video_mama_2025"
mkdir -p "$TARGET/Projects/billionblog"

# Create README files
cat > "$TARGET/README.txt" << 'EOF'
Media Archive Structure
=======================

/Originals/
  - Immutable vault of all original media files
  - Organized by device and date
  - NEVER delete from here

/Projects/
  - Project-specific folders
  - Contains symlinks to Originals + renders/exports

/Catalog/
  - Database and metadata
  - Sidecars (YAML), transcripts, thumbnails

/_ingest/
  - Temporary staging for new imports
  - Cleared after processing

Generated by: media-archive-toolkit
Date: $(date)
EOF

cat > "$TARGET/Originals/README.txt" << 'EOF'
Original Media Files - IMMUTABLE VAULT
======================================

This folder contains all original media files organized by:
- Device (camera/audio recorder)
- Year
- Date

NEVER:
- Delete files from this folder
- Rename files in this folder
- Move files out of this folder

Projects should reference these files via symlinks.
EOF

cat > "$TARGET/Projects/README.txt" << 'EOF'
Project Folders
===============

Each project has:
- Symlinks to source files in /Originals
- Rendered outputs
- Project-specific assets
- Metadata files

When project is complete, it can be archived.
EOF

echo -e "${GREEN}✓ Folder structure created successfully${NC}"
echo ""
echo -e "${YELLOW}Structure created:${NC}"

# Show tree if available, otherwise simple list
if command -v tree &> /dev/null; then
    tree -L 3 -d "$TARGET"
else
    find "$TARGET" -type d -maxdepth 3 | sort
fi

echo ""
echo -e "${GREEN}✓ Ready for migration!${NC}"